---
- name: Install and configure nginx
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  tasks:
    - name: Clean up broken nginx installation
      shell: |
        dpkg --configure -a
        apt-get -f install -y
      ignore_errors: true
      when: ansible_os_family == "Debian"

    - name: Remove broken nginx packages
      apt:
        name: 
          - nginx
          - nginx-core
          - nginx-common
        state: absent
        purge: true
      when: ansible_os_family == "Debian"
      ignore_errors: true

    - name: Update package cache
      apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install nginx without starting service
      apt:
        name: nginx
        state: present
      environment:
        RUNLEVEL: "1"
      when: ansible_os_family == "Debian"

    - name: Install nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create Hello World index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
                  <html lang="en">
                  <head>
                      <meta charset="UTF-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1.0">
                      <title>Chef Courier - Puppet Deployment</title>
                      <style>
                          body {
                              font-family: Arial, sans-serif;
                              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                              margin: 0;
                              padding: 20px;
                              min-height: 100vh;
                              display: flex;
                              align-items: center;
                              justify-content: center;
                          }
                          .container {
                              background: white;
                              padding: 40px;
                              border-radius: 10px;
                              box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                              text-align: center;
                              max-width: 600px;
                          }
                          h1 {
                              color: #333;
                              margin-bottom: 20px;
                          }
                          .info {
                              font-size: 18px;
                              color: #666;
                              line-height: 1.6;
                          }
                          .highlight {
                              color: #667eea;
                              font-weight: bold;
                          }
                          .tech-stack {
                              background: #f8f9fa;
                              padding: 20px;
                              border-radius: 5px;
                              margin-top: 20px;
                          }
                      </style>
                  </head>
                  <body>
                      <div class="container">
                          <h1>🚀 Hello Chef!</h1>
                          <div class="info">
                              <p>This is <span class="highlight">NGINX</span> installed using an Ansible Playbook <i>locally</i></p>
                              <p>Executed by <span class="highlight"><a href="https://www.chef.io/products/job-orchestration">Chef Courier</a></span></p>
                              
                              <div class="tech-stack">
                                  <h3>Technology Stack</h3>
                                  <ul style="list-style: none; padding: 0;">
                                      <li>🐧 <strong>OS:</strong> ${facts['os']['name']} ${facts['os']['release']['full']}</li>
                                      <li>🌐 <strong>Web Server:</strong> NGINX</li>
                                      <li>🤖 <strong>Configuration Management:</strong> Puppet</li>
                                      <li>👨‍🍳 <strong>Orchestration:</strong> Chef Courier</li>
                                  </ul>
                              </div>
                              
                              <p style="margin-top: 20px; font-size: 14px; color: #999;">
                                  Server: ${facts['networking']['fqdn']}
                              </p>
                          </div>
                      </div>
                  </body>
                  </html>

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
