---

- name: Courier Running Ansible Playbook Demo 
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines