---

- name: Courier Running Ansible Playbook Demo 
  hosts: localhost
  connection: local
  gather_facts: true
  environment:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines